# Generated by Django 5.0.4 on 2024-06-21 13:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDetail',
            fields=[
                ('patient_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_no', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('desc', models.TextField(blank=True, help_text="Provide details about You for consultant's reference.", null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AudioData',
            fields=[
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shifted.patientdetail')),
                ('audio_file', models.FileField(upload_to='audio_files/')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=30)),
                ('desc', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True)),
                ('cuisine', models.CharField(choices=[('Indian', 'Indian'), ('American', 'American'), ('Chinese', 'Chinese'), ('Japanese', 'Japanese')], max_length=10)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
