# Generated by Django 5.0.4 on 2024-06-21 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifted', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiodata',
            name='audio_id',
            field=models.UUIDField(default=None),
        ),
        migrations.AlterField(
            model_name='audiodata',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='shifted.patientdetail'),
        ),
    ]
