# Generated by Django 5.0.4 on 2024-06-21 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifted', '0002_audiodata_audio_id_alter_audiodata_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiodata',
            name='audio_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='audiodata',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='shifted.patientdetail'),
        ),
    ]
