# Generated by Django 5.0.4 on 2024-06-21 17:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifted', '0003_alter_audiodata_audio_id_alter_audiodata_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiodata',
            name='audio_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
