# Generated by Django 5.0.4 on 2024-06-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifted', '0004_alter_audiodata_audio_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiodata',
            name='audio_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
