# Generated by Django 5.0.4 on 2024-06-23 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifted', '0005_audiodata_audio_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiodata',
            name='audio_name',
            field=models.CharField(blank=True, help_text='Provide a name', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='PatientProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(blank=True, default='Unemployed', max_length=20, null=True)),
                ('vhi_score', models.PositiveIntegerField(blank=True, null=True)),
                ('smoker', models.CharField(choices=[('0', 'SMOKER'), ('1', 'NONSMOKER')], max_length=10)),
                ('cigar_per_day', models.PositiveIntegerField(blank=True, null=True)),
                ('alcohol_consumption', models.CharField(choices=[('1', 'HABITUAL DRINKER'), ('2', 'CASUAL DRINKER'), ('3', 'NONDRINKER')], default='3', max_length=1)),
                ('alcohol_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('waters_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('carbonated_drinks', models.CharField(choices=[('1', 'Always'), ('2', 'Almost Always'), ('3', 'Sometimes'), ('4', 'Almost Never'), ('5', 'Never')], default='3', max_length=1)),
                ('tomatoes', models.CharField(choices=[('1', 'Almost'), ('2', 'Always'), ('3', 'Sometimes'), ('4', 'Never')], default='3', max_length=1)),
                ('coffee', models.CharField(choices=[('1', 'Always'), ('2', 'Almost Always'), ('3', 'Sometimes'), ('4', 'Almost Never'), ('5', 'Never')], default='3', max_length=1)),
                ('coffee_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('chocolate', models.CharField(choices=[('1', 'Always'), ('2', 'Almost Always'), ('3', 'Sometimes'), ('4', 'Almost Never'), ('5', 'Never')], default='3', max_length=1)),
                ('chocolate_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('soft_cheese', models.CharField(choices=[('1', 'Always'), ('2', 'Almost Always'), ('3', 'Sometimes'), ('4', 'Almost Never'), ('5', 'Never')], default='3', max_length=1)),
                ('cheese_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('citrus_fruits', models.CharField(choices=[('1', 'Always'), ('2', 'Almost Always'), ('3', 'Sometimes'), ('4', 'Almost Never'), ('5', 'Never')], default='3', max_length=1)),
                ('citrus_fruits_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shifted.patientdetail')),
            ],
        ),
    ]
