# Generated by Django 5.0.4 on 2024-06-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifted', '0006_alter_audiodata_audio_name_patientproperties'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientproperties',
            name='rsi_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
