# Generated by Django 5.0.4 on 2024-06-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifted', '0007_patientproperties_rsi_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetail',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
