# Generated by Django 5.0.4 on 2024-06-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifted', '0008_alter_patientdetail_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetail',
            name='age',
            field=models.PositiveIntegerField(default=55),
        ),
    ]
