# Generated by Django 5.0.4 on 2024-06-25 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifted', '0010_remove_audiodata_patient_patientproperty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiodata',
            name='predicted_condition',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
