# Generated by Django 5.0.4 on 2024-06-25 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifted', '0011_audiodata_predicted_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetail',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='audiodata',
            name='predicted_condition',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(6)]),
        ),
    ]
