# Generated by Django 5.0.4 on 2024-06-25 13:22

import shifted.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifted', '0012_patientdetail_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiodata',
            name='audio_file',
            field=models.FileField(default=None, upload_to=shifted.models.AudioData.audio_file_path),
        ),
    ]
