# Generated by Django 5.0.4 on 2024-06-25 13:29

import shifted.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifted', '0013_alter_audiodata_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiodata',
            name='audio_file',
            field=models.FileField(default=None, upload_to=shifted.models.AudioData.audio_file_path, validators=[shifted.models.validate_file_extension]),
        ),
    ]
